"""Safe SQL execution tool with multi-layer defense guardrails for AgenticShop."""

from __future__ import annotations

import re
import time
from datetime import date, datetime
from decimal import Decimal
from typing import Any

import psycopg
from pydantic import BaseModel, Field

from app.db import get_db_connection

# Forbidden SQL command keywords that mutate state, schema, or system security
FORBIDDEN_KEYWORDS = {
    "DROP",
    "DELETE",
    "UPDATE",
    "INSERT",
    "ALTER",
    "TRUNCATE",
    "GRANT",
    "REVOKE",
    "COPY",
    "CREATE",
    "VACUUM",
    "EXECUTE",
    "CALL",
    "REINDEX",
    "CLUSTER",
}

# Regex to remove SQL comments (-- comment and /* comment */) before validation
COMMENT_PATTERN = re.compile(r"(--[^\n]*)|(/\*[\s\S]*?\*/)")

# Tool definition JSON Schema sent to the LLM (Universal / Provider-Agnostic)
SQL_TOOL_DEFINITION = {
    "name": "execute_sql_query",
    "description": (
        "Execute a read-only SQL query against the Shoply PostgreSQL database to answer "
        "business questions. Available tables: customers, products, orders, order_items, refunds. "
        "Only SELECT queries are allowed. Returns query rows and column metadata."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": (
                    "A valid read-only PostgreSQL SELECT statement. Do not modify data. "
                    "Use correct business definitions: revenue is SUM(total_amount) for completed orders; "
                    "monetary amounts are in INR (₹); dates are in '2026-MM-DD' format."
                ),
            }
        },
        "required": ["query"],
    },
}


class ExecuteSQLArgs(BaseModel):
    """Pydantic schema for validating SQL tool inputs from LLM tool calls."""

    query: str = Field(
        ...,
        description="A valid read-only PostgreSQL SELECT statement.",
    )


def clean_sql(query: str) -> str:
    """Strip comments and surrounding whitespace from a SQL query string."""
    cleaned = COMMENT_PATTERN.sub("", query)
    return cleaned.strip()


def validate_sql(query: str) -> None:
    """Validate that the query is strictly a read-only SELECT statement.

    Raises:
        ValueError: If the query is empty, contains multiple statements, or
                    includes forbidden mutating keywords.
    """
    cleaned = clean_sql(query)
    if not cleaned:
        raise ValueError("Query cannot be empty.")

    # Guard 1: Enforce that query starts with SELECT or WITH (for CTEs)
    first_word_match = re.match(r"^\s*([a-zA-Z]+)", cleaned)
    if not first_word_match:
        raise ValueError("Could not parse leading SQL keyword.")
    first_word = first_word_match.group(1).upper()
    if first_word not in ("SELECT", "WITH"):
        raise ValueError(
            f"Only read-only queries starting with SELECT or WITH are permitted. Found: '{first_word}'."
        )

    # Guard 2: Disallow multi-statement execution (e.g. 'SELECT 1; DROP TABLE orders;')
    # We strip trailing semicolon, then check if any internal semicolons remain
    without_trailing_semicolon = cleaned.rstrip(";").strip()
    if ";" in without_trailing_semicolon:
        raise ValueError("Multi-statement SQL queries separated by semicolons are not allowed.")

    # Guard 3: Tokenize words and reject forbidden DDL / DML keywords
    tokens = set(re.findall(r"\b[A-Za-z_]+\b", cleaned.upper()))
    intersection = tokens.intersection(FORBIDDEN_KEYWORDS)
    if intersection:
        forbidden = ", ".join(sorted(intersection))
        raise ValueError(f"Forbidden mutating keyword(s) detected: {forbidden}.")


def serialize_value(val: Any) -> Any:
    """Ensure database values serialize cleanly into JSON."""
    if isinstance(val, Decimal):
        return float(val)
    if isinstance(val, (date, datetime)):
        return val.isoformat()
    return val


def execute_sql_query(
    query: str,
    max_rows: int = 50,
    timeout_ms: int = 5000,
) -> dict[str, Any]:
    """Safely execute a read-only SQL query against the database.

    Args:
        query: The SQL query string generated by the LLM.
        max_rows: Maximum rows to return to prevent token blowup (default 50).
        timeout_ms: Statement timeout in milliseconds to prevent runaway queries.

    Returns:
        A structured dict with columns, rows, execution time, and error details (if any).
    """
    # Layer 1: Python pre-execution validation
    try:
        validate_sql(query)
    except ValueError as val_err:
        return {
            "success": False,
            "error": f"Validation Error: {str(val_err)}",
            "query": query,
        }

    start_time = time.perf_counter()

    # Layer 2 & 3: Database-level read-only transaction and statement timeout
    try:
        with get_db_connection() as conn:
            with conn.transaction():
                with conn.cursor() as cur:
                    # Enforce read-only transaction at the PostgreSQL engine level
                    cur.execute("SET TRANSACTION READ ONLY;")
                    # Enforce query execution timeout
                    cur.execute(f"SET LOCAL statement_timeout = '{int(timeout_ms)}ms';")

                    cur.execute(query)

                    if cur.description is None:
                        elapsed_ms = (time.perf_counter() - start_time) * 1000
                        return {
                            "success": True,
                            "columns": [],
                            "rows": [],
                            "row_count": 0,
                            "truncated": False,
                            "message": "Query executed successfully with no returned rows.",
                            "execution_time_ms": round(elapsed_ms, 2),
                            "query": query,
                        }

                    column_names = [col.name for col in cur.description]

                    # Layer 4: Fetch max_rows + 1 to detect truncation without unbounded memory use
                    raw_rows = cur.fetchmany(max_rows + 1)
                    truncated = len(raw_rows) > max_rows
                    result_rows = raw_rows[:max_rows]

                    formatted_rows = [
                        {col: serialize_value(val) for col, val in zip(column_names, row)}
                        for row in result_rows
                    ]

                    elapsed_ms = (time.perf_counter() - start_time) * 1000

                    message = None
                    if truncated:
                        message = (
                            f"Returned first {max_rows} rows (truncated). "
                            "Consider using aggregation (e.g. SUM, COUNT, AVG) or a LIMIT clause."
                        )

                    return {
                        "success": True,
                        "columns": column_names,
                        "rows": formatted_rows,
                        "row_count": len(formatted_rows),
                        "truncated": truncated,
                        "message": message,
                        "execution_time_ms": round(elapsed_ms, 2),
                        "query": query,
                    }

    except psycopg.Error as db_err:
        # Structured error output: Enables LLM to self-correct upon syntax or column errors
        return {
            "success": False,
            "error": f"PostgreSQL Error: {str(db_err).strip()}",
            "query": query,
        }
    except Exception as exc:
        return {
            "success": False,
            "error": f"Unexpected Execution Error: {str(exc)}",
            "query": query,
        }
