BEGIN;

CREATE TABLE customers (
    customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (length(trim(name)) > 0),
    signup_date date NOT NULL,
    region varchar(50) NOT NULL CHECK (region IN ('North', 'South', 'East', 'West')),
    city varchar(50) NOT NULL CHECK (length(trim(city)) > 0)
);

CREATE TABLE products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name text NOT NULL UNIQUE CHECK (length(trim(product_name)) > 0),
    category varchar(100) NOT NULL CHECK (length(trim(category)) > 0),
    price numeric(12, 2) NOT NULL CHECK (price > 0)
);

CREATE TABLE orders (
    order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES customers(customer_id),
    order_date date NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('completed', 'pending', 'cancelled')),
    total_amount numeric(12, 2) NOT NULL CHECK (total_amount > 0)
);

CREATE TABLE order_items (
    order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(order_id),
    product_id bigint NOT NULL REFERENCES products(product_id),
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(12, 2) NOT NULL CHECK (unit_price > 0)
);

CREATE TABLE refunds (
    refund_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(order_id),
    refund_date date NOT NULL,
    amount numeric(12, 2) NOT NULL CHECK (amount > 0),
    reason varchar(100) NOT NULL CHECK (length(trim(reason)) > 0)
);

CREATE INDEX orders_order_date_idx ON orders(order_date);
CREATE INDEX orders_customer_id_idx ON orders(customer_id);
CREATE INDEX order_items_order_id_idx ON order_items(order_id);
CREATE INDEX order_items_product_id_idx ON order_items(product_id);
CREATE INDEX refunds_order_id_idx ON refunds(order_id);
CREATE INDEX refunds_refund_date_idx ON refunds(refund_date);

COMMIT;
