"""Dynamic Task Planner for AgenticShop V2.

This module decomposes compound business questions into an ordered sequence
of atomic, verifiable sub-tasks before any SQL execution begins.
"""

from __future__ import annotations

import json
from typing import Any
from pydantic import BaseModel, Field

from app.agent.llm_client import BaseLLMClient, get_llm_client
from app.agent.prompts import DB_SCHEMA_PROMPT, BUSINESS_RULES_PROMPT


class PlanTask(BaseModel):
    """An individual atomic sub-task within an execution plan."""

    id: int = Field(..., description="1-indexed sequence number of the task")
    title: str = Field(..., description="Short summary title of the sub-task")
    objective: str = Field(
        ...,
        description="Detailed description of what data to retrieve or calculate",
    )
    sql_needed: bool = Field(
        default=True,
        description="True if this task requires querying PostgreSQL, False if it is a pure calculation or synthesis step",
    )
    expected_output_key: str = Field(
        ...,
        description="The variable name in the scratchpad where this task's finding will be stored",
    )


class ExecutionPlan(BaseModel):
    """Complete decomposed plan generated by the AI Planner."""

    reasoning: str = Field(
        ...,
        description="Strategic explanation of why the question was decomposed into these specific sub-tasks",
    )
    tasks: list[PlanTask] = Field(
        ...,
        min_length=1,
        max_length=6,
        description="The ordered list of atomic sub-tasks to execute sequentially",
    )


PLANNER_SYSTEM_PROMPT = f"""You are the Lead Planning Architect for Shoply's AI Business Analyst.

Your job is to read a user's business question and DECOMPOSE it into an ordered, atomic Execution Plan.
DO NOT execute SQL yourself. You only produce the strategic blueprint.

### Database Schema Context:
{DB_SCHEMA_PROMPT}

### Canonical Business Rules:
{BUSINESS_RULES_PROMPT}

### Planning Guidelines:
1. **Simple vs Compound Questions**:
   - If the question asks for a single metric (e.g. "What was our revenue in August?"), create a 1-task plan.
   - If the question is compound or comparative (e.g. "Compare revenue between July and August, find the top category, and check its refund rate"), break it into 2 to 4 distinct, atomic steps.

2. **Table Grain & Attribution Integrity**:
   - Remember that `refunds` is recorded at the `order_id` grain, while categories live at `order_items`.
   - When a plan requires comparing category-level refunds or rates, note in the objective to compute the cohort consistently.

3. **Date Baseline Consistency**:
   - For comparative tasks (e.g. company refund rate vs category refund rate), ensure both tasks target the exact same time window and date dimension.

4. **Output Format**:
   You MUST return ONLY a valid JSON object matching this schema:
   {{
     "reasoning": "Brief explanation of your decomposition strategy",
     "tasks": [
       {{
         "id": 1,
         "title": "Short title",
         "objective": "Exact description of what SQL or metric is needed",
         "sql_needed": true,
         "expected_output_key": "variable_name_for_scratchpad"
       }}
     ]
   }}
"""


def generate_execution_plan(
    question: str,
    client: BaseLLMClient | None = None,
) -> ExecutionPlan:
    """Decompose a natural language business question into an ExecutionPlan.

    Args:
        question: The user's natural language question.
        client: Optional pre-configured LLM client.

    Returns:
        A validated ExecutionPlan with ordered PlanTasks.
    """
    if client is None:
        client = get_llm_client()

    prompt = f"""Decompose the following user question into an optimal ExecutionPlan:

User Question: "{question}"

Respond with ONLY the JSON object. Do not include markdown code block formatting or backticks if possible."""

    response = client.chat(
        messages=[{"role": "user", "content": prompt}],
        system_prompt=PLANNER_SYSTEM_PROMPT,
        tools=None,
    )

    content = response.content or "{}"
    content_clean = content.strip()
    if content_clean.startswith("```json"):
        content_clean = content_clean[7:]
    elif content_clean.startswith("```"):
        content_clean = content_clean[3:]
    if content_clean.endswith("```"):
        content_clean = content_clean[:-3]
    content_clean = content_clean.strip()

    try:
        data = json.loads(content_clean)
        return ExecutionPlan.model_validate(data)
    except Exception as exc:
        # Fallback single-task plan if LLM failed to emit strict JSON
        return ExecutionPlan(
            reasoning=f"Direct execution plan (Fallback triggered: {exc})",
            tasks=[
                PlanTask(
                    id=1,
                    title="Execute Business Query",
                    objective=question,
                    sql_needed=True,
                    expected_output_key="primary_result",
                )
            ],
        )
